### ISSUE TITLE
Build core engine functionality

### ISSUE THREAD

**Issue by eonarheim** [eonarheim/BellTowerEscape#1]
We need to build the following functionality w/tests
* [x] Implement configurable # elevators/floors/people spawn
* [x] Issue commands to move up/down
* [x] Issue load/unload
* [x] Implement game timer logic (with testable clock)
* [x] Implement win/lose condition
* [x] Implement frustration on passengers (configurable value)

**Comment by FourierTransformer** [comment]
People spawn is complete. Might need some little tweaks - but it's there.

**Comment by FourierTransformer** [comment]
looks like we forgot win/lose and some game cleanup. it's in now! 94f82b9f15aa87075cfba035d292e362505e05b9
