### ISSUE TITLE
Turn information is not exposed through the game status

### ISSUE THREAD

**Issue by eonarheim** [eonarheim/BellTowerEscape#12]

**Comment by FourierTransformer** [comment]
Fixed the floors not being updated, and the correct elevators are being returned now. Meeples and Floors are still sketchy and not returning anything worthwhile.

**Comment by FourierTransformer** [comment]
Mostly Resolved. Frustration is still coming in as negative however - seems like a bug in the logics. Possibly related to #7

**Comment by FourierTransformer** [comment]
Fixed the negative frustration. However, meeple's still don't leave when frustrated, but that's a different issue.
