### ISSUE TITLE
Logic for Player 1 vs. Player 2

### ISSUE THREAD

**Issue by randombits01** [eonarheim/BellTowerEscape#22]
How does the agent know if it should send a player 1 or player 2 command, and how does agent 2 get the auth token and game id from player 1?

**Comment by eonarheim** [comment]
Each agent gets a unique secret token on connect, the game sorts out who is
who when commands are issued with that token

**Comment by randombits01** [comment]
So are you going to change the server code so "api/game/logon" automatically pairs people, and is that the service I should submit my agent with?

**Comment by eonarheim** [comment]
Last time we did something similar on the server, auto paired agents. It
would be good to have a flag to change the endpoint your agent is pointing
to "-endpoint http://elevators..."

**Comment by FourierTransformer** [comment]
Yeah, just submit using the standard "api/game/logon" - we'll take care of the rest!

The special player1/2 logon was just for people wanting to try multiple agents against themselves rather than the demo agent.

**Comment by randombits01** [comment]
Thanks for the clarification!
